from __future__ import annotations

from typing import Protocol
from uuid import UUID

from contract_intelligence.domain.entities.generated_contract import (
    GeneratedContract,
    GeneratedContractArtifact,
)
from contract_intelligence.domain.entities.source_document import (
    SourceDocument,
    SourceExtractionRun,
    SourceFieldEvidence,
    SourceParseRun,
    SourceSection,
    SourceSectionAnalysis,
    SourceSectionAnalysisReference,
    SourceSectionAnalysisRun,
    UploadStatus,
)
from contract_intelligence.domain.entities.template import (
    ContractTemplate,
    TemplateSection,
    TemplateVersion,
)


class SourceDocumentRepository(Protocol):
    async def commit(self) -> None: ...

    async def save(self, document: SourceDocument) -> SourceDocument: ...

    async def get_by_id(self, document_id: UUID) -> SourceDocument | None: ...

    async def get_by_hash(self, document_hash: str) -> SourceDocument | None: ...

    async def list_all(self) -> list[SourceDocument]: ...

    async def list_by_organization(self, organization_id: UUID) -> list[SourceDocument]: ...

    async def update_page_count(self, document_id: UUID, page_count: int) -> None: ...

    async def update_status(self, document_id: UUID, status: UploadStatus) -> None: ...

    async def save_parse_run(self, parse_run: SourceParseRun) -> SourceParseRun: ...

    async def save_extraction_run(
        self, extraction_run: SourceExtractionRun
    ) -> SourceExtractionRun: ...

    async def get_field_evidence_by_document_id(
        self, document_id: UUID
    ) -> list[SourceFieldEvidence]: ...

    async def get_field_evidence_by_id(self, evidence_id: UUID) -> SourceFieldEvidence | None: ...

    async def update_field_evidence(self, evidence: SourceFieldEvidence) -> None: ...

    async def save_field_evidence(self, evidence: SourceFieldEvidence) -> SourceFieldEvidence: ...

    async def update_parse_run(self, parse_run: SourceParseRun) -> None: ...

    async def update_extraction_run(self, extraction_run: SourceExtractionRun) -> None: ...

    async def save_analysis_run(
        self, run: SourceSectionAnalysisRun
    ) -> SourceSectionAnalysisRun: ...

    async def update_analysis_run(self, run: SourceSectionAnalysisRun) -> None: ...


class SourceSectionRepository(Protocol):
    # --- sections ---
    async def get_sections_by_document_id(self, document_id: UUID) -> list[SourceSection]: ...

    async def get_section_by_id(self, section_id: UUID) -> SourceSection | None: ...

    async def update_section(self, section: SourceSection) -> None: ...

    async def save_section(self, section: SourceSection) -> SourceSection: ...

    # --- analysis ---
    async def save_analysis(self, analysis: SourceSectionAnalysis) -> SourceSectionAnalysis: ...

    async def get_analysis_by_id(self, analysis_id: UUID) -> SourceSectionAnalysis | None: ...

    async def get_analyses_by_run_id(self, run_id: UUID) -> list[SourceSectionAnalysis]: ...

    async def update_analysis(self, analysis: SourceSectionAnalysis) -> None: ...

    # --- references ---
    async def save_analysis_reference(
        self, ref: SourceSectionAnalysisReference
    ) -> SourceSectionAnalysisReference: ...


class TemplateRepository(Protocol):
    async def save_template(self, template: ContractTemplate) -> ContractTemplate: ...

    async def get_template_by_id(self, template_id: UUID) -> ContractTemplate | None: ...

    async def save_version(self, version: TemplateVersion) -> TemplateVersion: ...

    async def get_version_by_id(self, version_id: UUID) -> TemplateVersion | None: ...

    async def get_section_by_id(self, section_id: UUID) -> TemplateSection | None: ...

    async def update_version(self, version: TemplateVersion) -> None: ...

    async def update_section(self, section: TemplateSection) -> None: ...

    async def update_template_current_version(
        self, template_id: UUID, version_id: UUID
    ) -> None: ...


class GeneratedContractRepository(Protocol):
    async def save(self, contract: GeneratedContract) -> GeneratedContract: ...

    async def get_by_id(self, contract_id: UUID) -> GeneratedContract | None: ...

    async def update(self, contract: GeneratedContract) -> None: ...

    async def save_artifact(
        self, artifact: GeneratedContractArtifact
    ) -> GeneratedContractArtifact: ...
