# Property Management
PROPERTY_CREATED = "PROPERTY_CREATED"

# Applicant Screening
APPLICANT_SCREENED = "APPLICANT_SCREENED"

# Customer Management
USER_REGISTERED = "USER_REGISTERED"
SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED"
SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED"
NOTIFICATION_SENT = "NOTIFICATION_SENT"
MEMBER_INVITED = "MEMBER_INVITED"
MEMBER_JOINED = "MEMBER_JOINED"
MEMBER_REMOVED = "MEMBER_REMOVED"
MEMBER_ROLE_CHANGED = "MEMBER_ROLE_CHANGED"

# Contract Intelligence
CONTRACT_ANALYZED = "CONTRACT_ANALYZED"
TEMPLATE_PUBLISHED = "TEMPLATE_PUBLISHED"
CONTRACT_GENERATED = "CONTRACT_GENERATED"
